server.port: 8081
spring:
  application.name: text-processor
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener.simple.retry:
      enabled: true
      initial-interval: 10s
      max-interval: 20s
      multiplier: 2
      max-attempts: 3
