server.port: 8080
spring:
  application.name: post
  datasource:
    username: sa
    password: 123
    url: jdbc:h2:file:~/posts-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
  h2.console.enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    listener.simple.retry:
      enabled: true
      initial-interval: 10s
      max-interval: 20s
      multiplier: 2
      max-attempts: 3
